plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

loom {
    accessWidenerPath = file("src/main/resources/kaleidoscope_cookery.accessWidener")
}

repositories {
	flatDir {
        dirs 'libs'
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    maven {
        // location of the maven that hosts JEI files since January 2023
        // Patchouli
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven {
        url = "https://maven.shedaniel.me"
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        url "https://maven.latvian.dev/releases"
        content {
            includeGroup "dev.latvian.mods"
            includeGroup "dev.latvian.apps"
        }
    }
    maven {
        url = "https://maven.architectury.dev"
        content {
            includeGroup "dev.architectury"
        }
    }
    maven {
        url = uri('libs')  // 指向重新组织后的libs文件夹
    }
    maven { url "https://mvn.devos.one/releases/" } // Porting Lib
    maven {
        url "https://maven.jamieswhiteshirt.com/libs-release" // Reach Entity Attributes (Required by Porting Lib)
        content {
            includeGroup "com.jamieswhiteshirt"
        }
    }
    maven {
        url "https://jitpack.io/" // Fabric ASM
        content {
            excludeGroup "io.github.fabricators_of_create"
        }
    }

    maven {
        url "https://registry.somethingcatchy.net/repository/maven-public/"
    }

    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }

    maven { url = "https://mvn.devos.one/releases/" }

    // 添加Maven中央仓库用于下载其他依赖
    mavenCentral()
    // Fabric相关仓库
    maven { url "https://maven.fabricmc.net/" }

    maven {
        name = "Greenhouse Maven"
        url = 'https://maven.greenhouse.lgbt/releases/'
    }
    maven { url "https://mvn.devos.one/releases/" } // Porting Lib
    maven {
        url "https://maven.jamieswhiteshirt.com/libs-release" // Reach Entity Attributes (Required by Porting Lib)
        content {
            includeGroup "com.jamieswhiteshirt"
        }
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "Ladysnake Libs"
        url = 'https://maven.ladysnake.org/releases'
    }
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
    maven {
        url "https://jitpack.io/" // Fabric ASM
        content {
            excludeGroup "io.github.fabricators_of_create"
        }
    }
    maven {
        url = "https://mvn.devos.one/snapshots/"
    }
    maven {
        url = "https://mvn.devos.one/releases/"
    }
    maven {
        url = "https://maven.createmod.net/"
    }
    maven {
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven"
    }
    maven {
        url = "https://maven.jamieswhiteshirt.com/libs-release"
    }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    modImplementation("vectorwing:FarmersDelight:${fdrf_version}") {
        exclude(group: "net.fabricmc")
    }
    modImplementation "curse.maven:trail-tales-delight-1198527:6492800"
    modImplementation "curse.maven:brewin-and-chewin-fabric-807512:5467339"
    modImplementation "curse.maven:rustic-delight-1106612:6140476"
    modImplementation(include("io.github.fabricators_of_create.Porting-Lib:loot:2.3.15+1.20.1"))
    modImplementation(include("io.github.fabricators_of_create.Porting-Lib:transfer:2.3.15+1.20.1"))
    modImplementation(include("io.github.fabricators_of_create.Porting-Lib:base:2.3.15+1.20.1"))
    modImplementation("maven.modrinth:forge-config-api-port:${project.forge_config_api_port_version}")
    modImplementation("mezz.jei:jei-${project.minecraft_version}-fabric:${project.jei_version}")
	// Mezz config
	modImplementation "maven.modrinth:7tEfOcA7:SYfAcmwJ"
    //Create
    modImplementation "com.simibubi.create:create-fabric:6.0.8.1+build.1744-mc1.20.1"
    //FTB
    modImplementation "curse.maven:ftb-library-fabric-438495:7296747"
    modImplementation "curse.maven:ftb-ultimine-fabric-448231:6899416"
    // AppleSkin
    modImplementation "maven.modrinth:EsAfCjCV:N5XeV21r"
    // Every Compat
    modCompileOnly("net.mehvahdjukaar:everycomp-fabric:1.20-2.9.26")
    modCompileOnly("net.mehvahdjukaar:moonlight-fabric:1.20-2.16.35")

    // REI 前置
    modImplementation "me.shedaniel.cloth:cloth-config-fabric:11.1.106"
    modImplementation "dev.architectury:architectury-fabric:9.2.14"
    // REI API for Forge (ForgeGradle)
    modCompileOnly "me.shedaniel:RoughlyEnoughItems-api-fabric:12.1.785"
    modCompileOnly "me.shedaniel:RoughlyEnoughItems-default-plugin-fabric:12.1.785"
    modCompileOnly "maven.modrinth:rei:12.1.785+fabric-fabric,1.20.1"

    // EMI
    //modCompileOnly "dev.emi:emi-fabric:1.1.22+1.20.1:api"
    //modCompileOnly "dev.emi:emi-fabric:1.1.22+1.20.1"
    modCompileOnly "maven.modrinth:emi:${emi_version}"

    modImplementation "maven.modrinth:jade:${jade_version}+fabric"

    // KubeJS
    modCompileOnly "dev.latvian.mods:kubejs-fabric:2001.6.5-build.26"
    modCompileOnly "dev.latvian.mods:rhino-fabric:2001.2.3-build.10"
    modRuntimeOnly "dev.architectury:architectury-fabric:9.2.14"
    modRuntimeOnly "maven.modrinth:probejs:6.0.0"

    modCompileOnly "dev.emi:trinkets:3.7.2"

    modImplementation "maven.modrinth:harvest-with-ease:9.4.0-fabric,1.20.1"
    modRuntimeOnly "maven.modrinth:cobweb:1.0.1-fabric,1.20.1"
    modImplementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:8.0.3"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
// Tests live in separate source sets and are excluded from the released mod.
dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.3'
}

test {
    useJUnitPlatform()
}
