plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}
archives_base_name = project.archives_base_name
version = project.mod_version
group = project.maven_group

loom {
    accessWidenerPath = file("src/main/resources/kaleidoscope_cookery.accessWidener")
}

base {
    archivesName = project.archives_base_name
}

repositories {
	maven { url "https://maven.shedaniel.me"}
    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com/"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "Ladysnake Libs"
        url = 'https://maven.ladysnake.org/releases'
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
        content {
            includeGroup "mezz.jei"
        }
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    maven {
        // location of the maven that hosts JEI files since January 2023
        // Patchouli
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven {
        name = "Greenhouse Maven"
        url = 'https://maven.greenhouse.lgbt/releases/'
    }
    maven {
        url "https://jitpack.io/" // Fabric ASM
        content {
            excludeGroup "io.github.fabricators_of_create"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Crystal Nest"
                url = "https://maven.crystalnest.it"
            }
        }
        filter {
            includeGroup "it.crystalnest"
        }
    }
    maven {
        url "https://registry.somethingcatchy.net/repository/maven-public/"
    }
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	modImplementation "curse.maven:ftb-ultimine-fabric-448231:7188393"
    modImplementation "curse.maven:ftb-library-fabric-438495:7260615"
    modImplementation("mezz.jei:jei-${project.minecraft_version}-fabric:${project.jei_version}")
    // Mezz config
	modImplementation "maven.modrinth:7tEfOcA7:Q5Yns1Qe"
    modImplementation "maven.modrinth:jade:${project.jade_version}"
    modCompileOnly "curse.maven:roughly-enough-items-310111:6199139"
    modImplementation "curse.maven:cloth-config-348521:5729125"
    modApi("me.shedaniel.cloth:basic-math:+")
    modImplementation "curse.maven:architectury-api-419699:5786326"
    modImplementation "dev.emi:trinkets:${trinkets_version}"
    //modCompileOnly "dev.emi:emi-fabric:${emi_version}:api"
    //modCompileOnly "dev.emi:emi-fabric:${emi_version}"
    modCompileOnly "maven.modrinth:emi:${emi_version}"
    // AppleSkin
    modImplementation "maven.modrinth:EsAfCjCV:b5ZiCjAr"
    // Every Compat
    modCompileOnly("net.mehvahdjukaar:everycomp-fabric:1.21-2.11.52")
    modCompileOnly("net.mehvahdjukaar:moonlight-fabric:1.21.1-3.6.5")

    // Delight family compact
    modImplementation("vectorwing:FarmersDelight:${fdrf_version}") {
        exclude(group: "net.fabricmc")
    }
    modImplementation "curse.maven:rustic-delight-1106612:7465640"
    modImplementation "curse.maven:trail-tales-delight-1198527:6492803"
    modImplementation "curse.maven:brewin-and-chewin-637808:7523546"
    modImplementation("house.greenhouse:greenhouseconfig:2.2.3+1.21.1-fabric")
    modImplementation("house.greenhouse:greenhouseconfig_toml:1.1.0")

    modImplementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:21.1.6"

    testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"
}

test {
    useJUnitPlatform()
    systemProperty "fabric.side", "server"
    workingDir layout.buildDirectory.dir("test-run").get().asFile
    doFirst {
        workingDir.mkdirs()
    }
}

processResources {
	inputs.property "version", project.version
	inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"
	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "projectName", project.name

	from("LICENSE") {
		rename { "${it}_${project.name}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
